-- AlterTable
ALTER TABLE "Employee" ADD COLUMN     "roleId" INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
